[project]
name = "eureka"
version = "0.1.0"
description = "An agentic scientific tool"
readme = "README.md"
authors = [
    { name = "raqkaaq", email = "eryan97@raqkaaq.com" }
]
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28",
    "pydantic>=2.13.5",
    "pydantic-ai-slim[openai]>=2.52.0",
    "PyYAML>=6.0.3,<7",
]

[project.scripts]
eureka = "eureka:main"

[build-system]
requires = ["uv_build>=0.11.8,<0.12.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = ["eureka", "radar"]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
