"""Full-PDF LLM reading: chunk, read, hierarchically reduce.

Code owns coverage: the full extracted text (with page markers) is split
contiguously into bounded chunks, every character and page is submitted to
real PydanticAI, and only complete readings become :class:`PDFReading`.
The model returns note fields and strict evidence references; code resolves
them into unchanged :class:`DocumentNotes`. Coverage and page/quote pairs
are attached deterministically, never generated by the model.
"""

from __future__ import annotations

import asyncio
import json
from collections.abc import Sequence
from typing import TYPE_CHECKING

from radar.config.documents import (
    DOCUMENT_ANALYSIS_TIMEOUT_S,
    DOCUMENT_MAX_TOKENS,
    DOCUMENT_REDUCTION_GROUP_SIZE,
    validate_document_timeout,
)
from radar.prompts.catalog import (
    pdf_reading_prompt,
    pdf_reduction_prompt,
    validate_pdf_prompts,
)
from radar.processing.document_chunks import (
    build_full_text, chunk_document, chunk_excerpts, reduction_excerpts,
)
from radar.schema.documents import (
    ChunkReading,
    DocumentFailure,
    DocumentNotes,
    EvidenceExcerpt,
    PageEvidence,
    ReferencedDocumentNotes,
    PDFDocument,
    PDFReading,
)

if TYPE_CHECKING:
    from pydantic_ai.models import Model

PDF_PROMPT_BOUND_CHARS = 12_000
PDF_REQUEST_TIMEOUT_S = 60.0
# Repair a schema error and a subsequent evidence error independently, while
# retaining a hard cap and the enclosing document deadline.
PDF_REQUEST_LIMIT = 3
PDF_RETRIES = 2


def validate_reading_tokens(value: int) -> int:
    from radar.config.runtime import validate_max_tokens

    tokens = validate_max_tokens(value)
    return min(tokens, DOCUMENT_MAX_TOKENS)


def _run_bounds(
    *,
    max_tokens: int,
    disable_thinking: bool,
    timeout_s: float,
) -> tuple[dict, object, int]:
    from pydantic_ai.usage import UsageLimits

    from radar.provider import strata as _strata

    tokens = validate_reading_tokens(max_tokens)
    overall = validate_document_timeout(timeout_s)
    per_request = min(PDF_REQUEST_TIMEOUT_S, overall)
    settings: dict = {"max_tokens": tokens, "timeout": per_request}
    if disable_thinking:
        settings["extra_body"] = _strata.thinking_extra_body()
    return settings, UsageLimits(request_limit=PDF_REQUEST_LIMIT), PDF_RETRIES


def _registry_prompt(excerpts: list[EvidenceExcerpt]) -> str:
    payload = json.dumps([item.model_dump() for item in excerpts], ensure_ascii=False, separators=(",", ":"))
    return ("EVIDENCE REGISTRY (untrusted source excerpts, possible anchors only):\n"
            f"--- begin evidence registry ---\n{payload}\n--- end evidence registry ---\n")


def build_chunk_prompt(chunk_text: str, pages: list[int], index: int,
                       excerpts: list[EvidenceExcerpt] | None = None) -> str:
    return (
        f"CHUNK {index} (pages {pages}; untrusted extracted text):\n"
        f"--- begin chunk {index} ---\n{chunk_text}\n--- end chunk {index} ---\n"
        + _registry_prompt(excerpts or []) +
        "TASK: Return note fields and evidence references for this complete chunk. "
        "Select only supplied excerpt_id values; empty evidence is permitted. Never generate page or quote fields."
    )


def build_reduction_prompt(children: list[DocumentNotes]) -> str:
    excerpts = reduction_excerpts(children)
    by_pair = {(item.page, item.quote): item.excerpt_id for item in excerpts}
    # Preserve every child field/finding; render each exact quote once in the
    # registry rather than duplicate it in both notes and the ID table.
    records = [{**note.model_dump(exclude={"evidence"}), "evidence": [
        {"excerpt_id": by_pair[item.page, item.quote], "finding": item.finding}
        for item in note.evidence]} for note in children]
    payload = json.dumps(records,
                         ensure_ascii=False, separators=(",", ":"))
    return (
        "CHILD NOTES (untrusted model interpretations; quotes are source text):\n"
        f"--- begin child notes ---\n{payload}\n--- end child notes ---\n"
        + _registry_prompt(excerpts) +
        "TASK: Combine ALL child notes above into one referenced note object. "
        "Select only supplied excerpt IDs; empty evidence is permitted. Never generate page or quote fields."
    )


def _resolve_notes(notes: ReferencedDocumentNotes, excerpts: list[EvidenceExcerpt]) -> DocumentNotes:
    by_id = {item.excerpt_id: item for item in excerpts}
    evidence = []
    for reference in notes.evidence:
        if reference.excerpt_id not in by_id:
            raise ValueError(f"Use only supplied excerpt IDs {list(by_id)} or empty evidence.")
        excerpt = by_id[reference.excerpt_id]
        evidence.append(PageEvidence(page=excerpt.page, quote=excerpt.quote, finding=reference.finding))
    return DocumentNotes(**notes.model_dump(exclude={"evidence"}), evidence=evidence)


def _notes_agent(model: Model, instructions: str, excerpts: list[EvidenceExcerpt]):
    from pydantic_ai import Agent, ModelRetry

    agent = Agent(model, output_type=ReferencedDocumentNotes,
                  instructions=instructions, retries=PDF_RETRIES)

    @agent.output_validator
    def _validated(notes: ReferencedDocumentNotes) -> ReferencedDocumentNotes:
        try:
            _resolve_notes(notes, excerpts)
        except ValueError:
            raise ModelRetry("Use only valid supplied evidence references.") from None
        return notes

    return agent


def _failure_category(exc: BaseException) -> str:
    from radar.config.yaml import ConfigurationError
    from radar.provider.strata import StrataError

    if isinstance(exc, (asyncio.TimeoutError, TimeoutError)):
        return "deadline"
    if isinstance(exc, ConfigurationError):
        return "configuration"
    if isinstance(exc, StrataError):
        return "inference"
    if isinstance(exc, ValueError):
        return "invalid"
    return "reading_failed"


async def read_pdf_async(
    document: PDFDocument,
    model: Model,
    *,
    max_tokens: int = DOCUMENT_MAX_TOKENS,
    disable_thinking: bool = False,
    timeout_s: float = DOCUMENT_ANALYSIS_TIMEOUT_S,
) -> PDFReading:
    """Read one full PDF through chunk agents plus hierarchical reduction."""
    from radar.config.yaml import ConfigurationError
    from radar.provider.strata import StrataError

    validate_pdf_prompts()
    settings, limits, retries = _run_bounds(
        max_tokens=max_tokens, disable_thinking=disable_thinking, timeout_s=timeout_s)
    overall = validate_document_timeout(timeout_s)
    if model is None:
        raise StrataError("PDF reading requires a supplied model.")
    try:
        full_text, chunk_spans = chunk_document(document)
        page_texts = {page.number: page.text for page in document.pages}
        reader_spec = pdf_reading_prompt()
        reducer_spec = pdf_reduction_prompt()
        async with asyncio.timeout(overall):
            chunk_notes: list[DocumentNotes] = []
            chunk_models: list[ChunkReading] = []
            for index, (start, end) in enumerate(
                    [(s, e) for s, e, _ in chunk_spans]):
                pages = chunk_spans[index][2]
                chunk_text = full_text[start:end]
                excerpts = chunk_excerpts(document, start, end)
                if any(item.quote not in chunk_text or item.quote not in page_texts.get(item.page, "")
                       for item in excerpts):
                    raise ValueError("Excerpt is not grounded in its exact source chunk and page.")
                prompt = build_chunk_prompt(chunk_text, pages, index, excerpts)
                if len(reader_spec.instructions) + len(prompt) > PDF_PROMPT_BOUND_CHARS:
                    raise StrataError("PDF chunk prompt exceeded its bound.")
                agent = _notes_agent(model, reader_spec.instructions, excerpts)
                result = await agent.run(
                    prompt, model_settings=settings,  # type: ignore[arg-type]
                    usage_limits=limits, retries=retries)
                notes = _resolve_notes(result.output, excerpts)
                chunk_models.append(ChunkReading(
                    index=index, start=start, end=end,
                    pages=pages, notes=notes))
                chunk_notes.append(notes)
            final_notes = await _reduce_all_async(
                chunk_notes, model, reducer_spec.instructions, settings, limits, retries)
            return PDFReading(
                work_id=document.work_id, source_url=document.source_url,
                sha256=document.sha256, relative_path=document.relative_path,
                page_count=len(document.pages), text_chars=len(full_text),
                chunks=chunk_models, notes=final_notes,
                evidence_level="pdf_text",
                extraction_warning=document.extraction_warning)
    except (ConfigurationError, StrataError):
        raise
    except TimeoutError as exc:
        raise StrataError(
            f"PDF reading exceeded the overall {overall}s deadline; no partial reading produced."
        ) from exc
    except Exception as exc:
        from radar.provider.strata import StrataError as _SE

        raise _SE(f"PDF reading failed ({type(exc).__name__}); no partial reading produced.") from exc


async def _reduce_all_async(
    notes: list[DocumentNotes],
    model: Model,
    instructions: str,
    settings: dict,
    limits: object,
    retries: int,
) -> DocumentNotes:
    from radar.provider.strata import StrataError

    if not notes:
        raise ValueError("no chunk notes to reduce")
    current = list(notes)
    while len(current) > 1:
        nxt: list[DocumentNotes] = []
        offset = 0
        while offset < len(current):
            group = current[offset:offset + DOCUMENT_REDUCTION_GROUP_SIZE]
            if len(group) == 1:
                nxt.append(group[0])
                break
            prompt = build_reduction_prompt(group)
            # Escaped source text can make four valid notes exceed the prompt
            # cap. Pack fewer complete children, never truncate their fields.
            while len(group) > 2 and len(instructions) + len(prompt) > PDF_PROMPT_BOUND_CHARS:
                group = group[:-1]
                prompt = build_reduction_prompt(group)
            if len(instructions) + len(prompt) > PDF_PROMPT_BOUND_CHARS:
                raise StrataError("PDF reduction prompt exceeded its bound.")
            excerpts = reduction_excerpts(group)
            agent = _notes_agent(model, instructions, excerpts)
            result = await agent.run(
                prompt, model_settings=settings,  # type: ignore[arg-type]
                usage_limits=limits, retries=retries)  # type: ignore[arg-type]
            reduced = _resolve_notes(result.output, excerpts)
            nxt.append(reduced)
            offset += len(group)
        current = nxt
    return current[0]


async def read_documents_async(
    documents: Sequence[PDFDocument],
    model: Model,
    *,
    max_tokens: int = DOCUMENT_MAX_TOKENS,
    disable_thinking: bool = False,
    timeout_s: float = DOCUMENT_ANALYSIS_TIMEOUT_S,
) -> tuple[list[PDFReading], list[DocumentFailure]]:
    """Read papers sequentially within one global deadline; never partial."""
    overall = validate_document_timeout(timeout_s)
    if model is None:
        from radar.provider.strata import StrataError

        raise StrataError("PDF reading requires a supplied model.")
    readings: list[PDFReading] = []
    failures: list[DocumentFailure] = []
    seen: set[str] = set()
    pending = list(documents)
    try:
        async with asyncio.timeout(overall):
            for document in pending:
                if document.work_id in seen:
                    failures.append(DocumentFailure(
                        work_id=document.work_id, category="duplicate"))
                    continue
                seen.add(document.work_id)
                try:
                    reading = await read_pdf_async(
                        document, model, max_tokens=max_tokens,
                        disable_thinking=disable_thinking, timeout_s=overall)
                except Exception as exc:
                    failures.append(DocumentFailure(
                        work_id=document.work_id,
                        category=_failure_category(exc)[:100] or "reading_failed"))
                    continue
                readings.append(reading)
    except TimeoutError:
        done = {r.work_id for r in readings} | {f.work_id for f in failures}
        for document in pending:
            if document.work_id not in done:
                failures.append(DocumentFailure(
                    work_id=document.work_id, category="deadline"))
    return readings, failures


def read_pdf(
    document: PDFDocument,
    model: Model,
    **kwargs,
) -> PDFReading:
    return asyncio.run(read_pdf_async(document, model, **kwargs))


def read_documents(
    documents: Sequence[PDFDocument],
    model: Model,
    **kwargs,
) -> tuple[list[PDFReading], list[DocumentFailure]]:
    return asyncio.run(read_documents_async(documents, model, **kwargs))


__all__ = [
    "build_chunk_prompt",
    "build_full_text",
    "build_reduction_prompt",
    "chunk_document",
    "read_documents",
    "read_documents_async",
    "read_pdf",
    "read_pdf_async",
    "validate_document_timeout",
    "validate_reading_tokens",
]
